# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 07:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Books_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookdb',
            name='book_author',
        ),
    ]
